language: python

python:
    - "2.6"
    - "2.7"

before_install:
    - sudo apt-get update

install:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install pybuilder
    - pip install pytest
    - pip install mongoengine
    - pip install beautifulsoup4
    - pip install cherrypy
    - pip install nose

before_script:
    - pyb install_dependencies

script:
    - pyb

notifications:
    email:
        recipients:
            - ray.jiang@mail.utoronto.ca
            - max.jeong@mail.utoronto.ca
            - chunhong.cho@mail.utoronto.ca
            - chanal12@mail.utoronto.ca
            - ali.mehdi@mail.utoronto.ca
        on_success: always
        on_failure: always

#install: "pip install dependencies"

