language: python

python:
    - "2.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install xvfb

install:
    - pip install -r requirements.txt
    - sudo sh dryscrape.sh

before_script:
    - pyb install_dependencies

script:
    - xvfb-run pyb

notifications:
    email:
        recipients:
            - ray.jiang@mail.utoronto.ca
            - max.jeong@mail.utoronto.ca
            - chunhong.cho@mail.utoronto.ca
            - chanal12@mail.utoronto.ca
            - ali.mehdi@mail.utoronto.ca
        on_success: always
        on_failure: always

#install: "pip install dependencies"

