language: python

python:
    - "2.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install libqt4-dev libqtwebkit-dev qt4-qmake build-essential python-lxml python-pip
    - sudo apt-get install xvfb

install:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - git clone https://github.com/niklasb/dryscrape.git dryscrape
    - cd dryscrape
    - pip install -r requirements.txt
    - python setup.py install
    - cd ..

before_script:
    - pyb install_dependencies

script:
    - xvfb-run pyb

notifications:
    email:
        recipients:
            - ray.jiang@mail.utoronto.ca
            - max.jeong@mail.utoronto.ca
            - chunhong.cho@mail.utoronto.ca
            - chanal12@mail.utoronto.ca
            - ali.mehdi@mail.utoronto.ca
        on_success: always
        on_failure: always

#install: "pip install dependencies"

